name: Daily FundBot Scraper

on:
  schedule:
    # Runs every day at 08:00 UTC
    - cron: '0 8 * * *'
  workflow_dispatch: # Allows manual triggering

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 # Fetch all history for git operations

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9' # Use Python 3.9, adjust if needed

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run FundBot
      env:
        GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
        DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
      run: python main.py

    - name: Commit and push changes (fundbot.db)
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add fundbot.db
        git commit -m "feat: Update fundbot.db with new convocatorias" || echo "No changes to commit"
        git push
